# App for Lottery Addiction

<img src=https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Lotto_649_logo.svg/1200px-Lotto_649_logo.svg.png width="300">

The purpose of this project is to build an application to help lottery addicts better estimate their chances of winning, specifically for the 6/49 lottery.

For the first version of the app, the focus will be on the  [6/49](https://en.wikipedia.org/wiki/Lotto_6/49) lottery and build functions that enable users to answer questions like:
1. What is the probability of winning the big prize with a single ticket?
2. What is the probability of winning the big prize if we play 40 different tickets (or any other number)?
3. What is the probability of having at least five (or four, or three, or two) winning numbers on a single ticket?

Additionally, the app should also consider historical data coming from the national 6/49 lottery game in Canada. The data set has data for 3,665 drawings, dating from 1982 to 2018.

### Core functions
Throughout the project, probabilities and combinations will be calculated often. The initial step is to write two functions:
- A function that calculates factorials; and
- A function that calculates combinations.

In [1]:
def factorial(n):
    final = 1
    for i in range(1, n+1):
        final *= i
    return final

def combinations(n, k):
    return factorial(n)/(factorial(k)*factorial(n-k))

### One-ticket probability
On this section, the focus is on writing a function that calculates the probability of winning the big prize.

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. A player wins the big prize if the six numbers on their tickets match all the six numbers drawn. If a player has a ticket with the numbers {13, 22, 24, 27, 42, 44}, he only wins the big prize if the numbers drawn are {13, 22, 24, 27, 42, 44}. If only one number differs, the player doesn't win.

Players should be able to calculate the probability of winning the big prize with the various numbers they play on a single ticket (for each ticket a player chooses six numbers out of 49). Thus, a function should be built that calculates the probability of winning the big prize for any given ticket.

In the app, these should also be considered:

- Inside the app, the user inputs six different numbers from 1 to 49.
- Under the hood, the six numbers will come as a Python list, which will serve as the single input to our function.
- The function should print the probability value in a friendly way â€” in a way that people without any probability training are able to understand.

In [2]:
def one_ticket_probability(a_list):
    total_outcomes = combinations(49, len(a_list))
    probability = 1/total_outcomes
    return print('The probability of winning with {} is {:.6%}'.format(a_list, probability))

In [3]:
one_ticket_probability([13, 22, 24, 27, 42, 44])

The probability of winning with [13, 22, 24, 27, 42, 44] is 0.000007%

### Historical Data Check for Canada Lottery
Users should also be able to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

The historical dataset can be downloaded from [Kaggle](https://www.kaggle.com/datasets/datascienceai/lottery-dataset).

The data set contains historical data for 3,665 drawings (each row shows data for a single drawing), dating from 1982 to 2018. For each drawing, we can find the six numbers drawn in the following six columns:

- `NUMBER DRAWN 1`
- `NUMBER DRAWN 2`
- `NUMBER DRAWN 3`
- `NUMBER DRAWN 4`
- `NUMBER DRAWN 5`
- `NUMBER DRAWN 6`

In [4]:
import pandas as pd

In [5]:
results_649 = pd.read_csv('649.csv')
print(results_649.shape)
results_649

(3665, 11)

,PRODUCT,DRAW NUMBER,SEQUENCE NUMBER,DRAW DATE,NUMBER DRAWN 1,NUMBER DRAWN 2,NUMBER DRAWN 3,NUMBER DRAWN 4,NUMBER DRAWN 5,NUMBER DRAWN 6,BONUS NUMBER
0,649,1,0,6/12/1982,3,11,12,14,41,43,13
1,649,2,0,6/19/1982,8,33,36,37,39,41,9
2,649,3,0,6/26/1982,1,6,23,24,27,39,34
3,649,4,0,7/3/1982,3,9,10,13,20,43,34
4,649,5,0,7/10/1982,5,14,21,31,34,47,45
5,649,6,0,7/17/1982,8,20,21,25,31,41,33
6,649,7,0,7/24/1982,18,25,28,33,36,42,7
7,649,8,0,7/31/1982,7,16,17,31,40,48,26
8,649,9,0,8/7/1982,5,10,23,27,37,38,33
9,649,10,0,8/14/1982,4,15,30,37,46,48,3
10,649,11,0,8/21/1982,7,9,21,33,38,42,45
11,649,12,0,8/28/1982,11,17,19,20,36,43,9
12,649,13,0,9/4/1982,7,14,17,20,37,47,34
13,649,14,0,9/11/1982,25,28,29,30,35,44,3
14,649,15,0,9/18/1982,8,18,36,39,41,47,31
15,649,16,0,9/25/1982,9,12,13,14,44,48,18
16,649,17,0,10/2/1982,4,14,18,40,43,44,5
17,649,18,0,10/9/1982,13,16,18,34,35,36,26
18,649,19,0,10/16/1982,11,23,25,28,29,36,27
19,649,20,0,10/23/1982,7,18,23,25,37,45,39
20,649,21,0,10/30/1982,11,18,19,31,37,45,41
21,649,22,0,11/6/1982,8,14,16,18,31,48,45
22,649,23,0,11/13/1982,4,11,23,24,25,45,41
23,649,24,0,11/20/1982,3,4,19,33,34,48,39
24,649,25,0,11/27/1982,5,17,21,28,30,43,36
25,649,26,0,12/4/1982,6,17,24,36,38,46,29
26,649,27,0,12/11/1982,4,9,10,11,43,46,3
27,649,28,0,12/18/1982,7,13,23,32,33,45,36
28,649,29,0,12/25/1982,11,18,22,28,35,37,42
29,649,30,0,1/1/1983,25,26,31,35,45,48,12
...,...,...,...,...,...,...,...,...,...,...,...
3635,649,3562,0,3/10/2018,2,10,28,43,44,48,39
3636,649,3563,0,3/14/2018,1,9,10,19,33,43,21
3637,649,3564,0,3/17/2018,16,17,35,43,44,46,49
3638,649,3565,0,3/21/2018,1,5,9,12,39,41,28
3639,649,3566,0,3/24/2018,9,11,28,30,45,49,5
3640,649,3567,0,3/28/2018,11,12,19,24,28,46,39
3641,649,3568,0,3/31/2018,3,7,22,26,43,47,48
3642,649,3569,0,4/4/2018,6,8,9,13,34,40,4
3643,649,3570,0,4/7/2018,18,22,36,40,47,49,32
3644,649,3571,0,4/11/2018,3,7,10,32,41,43,33
3645,649,3572,0,4/14/2018,1,11,19,36,48,49,9
3646,649,3573,0,4/18/2018,12,17,19,22,27,39,38
3647,649,3574,0,4/21/2018,12,19,20,30,41,49,9
3648,649,3575,0,4/25/2018,10,14,15,16,40,46,6
3649,649,3576,0,4/28/2018,24,31,33,34,44,46,10
3650,649,3577,0,5/2/2018,4,7,28,36,37,49,21
3651,649,3578,0,5/5/2018,4,18,24,26,33,48,34
3652,649,3579,0,5/9/2018,15,17,21,24,36,37,32
3653,649,3580,0,5/12/2018,6,17,21,34,37,44,13
3654,649,3581,0,5/16/2018,19,21,28,30,39,46,7
3655,649,3582,0,5/19/2018,14,15,28,34,38,44,30
3656,649,3583,0,5/23/2018,4,9,15,20,42,44,31
3657,649,3584,0,5/26/2018,12,13,16,23,39,44,2
3658,649,3585,0,5/30/2018,9,14,17,21,38,39,22
3659,649,3586,0,6/2/2018,2,26,32,40,45,49,29
3660,649,3587,0,6/6/2018,10,15,23,38,40,41,35
3661,649,3588,0,6/9/2018,19,25,31,36,46,47,26
3662,649,3589,0,6/13/2018,6,22,24,31,32,34,16
3663,649,3590,0,6/16/2018,2,15,21,31,38,49,8
3664,649,3591,0,6/20/2018,14,24,31,35,37,48,17

After exploring the dataset, I built a function that will enable users to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

Additional considerations:

- Inside the app, the user inputs six different numbers from 1 to 49.
- Under the hood, the six numbers will come as a Python list and serve as an input to our function.
- The function should print:
    - the number of times the combination selected occurred in the Canada data set; and
    - the probability of winning the big prize in the next drawing with that combination.

In [6]:
def extract_numbers(series):
    return set(series)

The function number takes a row and returns a set with the winning number. This will be used in combination with the `DataFrame.apply()` method to extract all the winning numbers.

In [7]:
results_649

,PRODUCT,DRAW NUMBER,SEQUENCE NUMBER,DRAW DATE,NUMBER DRAWN 1,NUMBER DRAWN 2,NUMBER DRAWN 3,NUMBER DRAWN 4,NUMBER DRAWN 5,NUMBER DRAWN 6,BONUS NUMBER
0,649,1,0,6/12/1982,3,11,12,14,41,43,13
1,649,2,0,6/19/1982,8,33,36,37,39,41,9
2,649,3,0,6/26/1982,1,6,23,24,27,39,34
3,649,4,0,7/3/1982,3,9,10,13,20,43,34
4,649,5,0,7/10/1982,5,14,21,31,34,47,45
5,649,6,0,7/17/1982,8,20,21,25,31,41,33
6,649,7,0,7/24/1982,18,25,28,33,36,42,7
7,649,8,0,7/31/1982,7,16,17,31,40,48,26
8,649,9,0,8/7/1982,5,10,23,27,37,38,33
9,649,10,0,8/14/1982,4,15,30,37,46,48,3
10,649,11,0,8/21/1982,7,9,21,33,38,42,45
11,649,12,0,8/28/1982,11,17,19,20,36,43,9
12,649,13,0,9/4/1982,7,14,17,20,37,47,34
13,649,14,0,9/11/1982,25,28,29,30,35,44,3
14,649,15,0,9/18/1982,8,18,36,39,41,47,31
15,649,16,0,9/25/1982,9,12,13,14,44,48,18
16,649,17,0,10/2/1982,4,14,18,40,43,44,5
17,649,18,0,10/9/1982,13,16,18,34,35,36,26
18,649,19,0,10/16/1982,11,23,25,28,29,36,27
19,649,20,0,10/23/1982,7,18,23,25,37,45,39
20,649,21,0,10/30/1982,11,18,19,31,37,45,41
21,649,22,0,11/6/1982,8,14,16,18,31,48,45
22,649,23,0,11/13/1982,4,11,23,24,25,45,41
23,649,24,0,11/20/1982,3,4,19,33,34,48,39
24,649,25,0,11/27/1982,5,17,21,28,30,43,36
25,649,26,0,12/4/1982,6,17,24,36,38,46,29
26,649,27,0,12/11/1982,4,9,10,11,43,46,3
27,649,28,0,12/18/1982,7,13,23,32,33,45,36
28,649,29,0,12/25/1982,11,18,22,28,35,37,42
29,649,30,0,1/1/1983,25,26,31,35,45,48,12
...,...,...,...,...,...,...,...,...,...,...,...
3635,649,3562,0,3/10/2018,2,10,28,43,44,48,39
3636,649,3563,0,3/14/2018,1,9,10,19,33,43,21
3637,649,3564,0,3/17/2018,16,17,35,43,44,46,49
3638,649,3565,0,3/21/2018,1,5,9,12,39,41,28
3639,649,3566,0,3/24/2018,9,11,28,30,45,49,5
3640,649,3567,0,3/28/2018,11,12,19,24,28,46,39
3641,649,3568,0,3/31/2018,3,7,22,26,43,47,48
3642,649,3569,0,4/4/2018,6,8,9,13,34,40,4
3643,649,3570,0,4/7/2018,18,22,36,40,47,49,32
3644,649,3571,0,4/11/2018,3,7,10,32,41,43,33
3645,649,3572,0,4/14/2018,1,11,19,36,48,49,9
3646,649,3573,0,4/18/2018,12,17,19,22,27,39,38
3647,649,3574,0,4/21/2018,12,19,20,30,41,49,9
3648,649,3575,0,4/25/2018,10,14,15,16,40,46,6
3649,649,3576,0,4/28/2018,24,31,33,34,44,46,10
3650,649,3577,0,5/2/2018,4,7,28,36,37,49,21
3651,649,3578,0,5/5/2018,4,18,24,26,33,48,34
3652,649,3579,0,5/9/2018,15,17,21,24,36,37,32
3653,649,3580,0,5/12/2018,6,17,21,34,37,44,13
3654,649,3581,0,5/16/2018,19,21,28,30,39,46,7
3655,649,3582,0,5/19/2018,14,15,28,34,38,44,30
3656,649,3583,0,5/23/2018,4,9,15,20,42,44,31
3657,649,3584,0,5/26/2018,12,13,16,23,39,44,2
3658,649,3585,0,5/30/2018,9,14,17,21,38,39,22
3659,649,3586,0,6/2/2018,2,26,32,40,45,49,29
3660,649,3587,0,6/6/2018,10,15,23,38,40,41,35
3661,649,3588,0,6/9/2018,19,25,31,36,46,47,26
3662,649,3589,0,6/13/2018,6,22,24,31,32,34,16
3663,649,3590,0,6/16/2018,2,15,21,31,38,49,8
3664,649,3591,0,6/20/2018,14,24,31,35,37,48,17

In [8]:
winning_numbers = results_649.iloc[:,4:10].apply(extract_numbers, axis=1)

In [9]:
winning_numbers.head(10)

0     {3, 41, 11, 12, 43, 14}
1     {33, 36, 37, 39, 8, 41}
2      {1, 6, 39, 23, 24, 27}
3      {3, 9, 10, 43, 13, 20}
4     {34, 5, 14, 47, 21, 31}
5     {8, 41, 20, 21, 25, 31}
6    {33, 36, 42, 18, 25, 28}
7     {7, 40, 16, 17, 48, 31}
8     {5, 38, 37, 10, 23, 27}
9     {4, 37, 46, 15, 48, 30}
dtype: object

It looks like the process was successful in extract each set of winning numbers from all of the historical drawings.

In [10]:
def check_historical_occurence(user_no, winning_no_series):
    user_set = set(user_no)
    matches = winning_no_series == user_set
    occurence = sum(matches)
    print('The combination entered has occurred {} times in the past.'.format(occurence))
    one_ticket_probability(user_no)

In [11]:
test_numbers = [13, 22, 24, 27, 42, 44]
check_historical_occurence(test_numbers, winning_numbers)

The combination entered has occurred 0 times in the past.
The probability of winning with [13, 22, 24, 27, 42, 44] is 0.000007%

In [12]:
pos_numbers = [3, 41, 11, 12, 43, 14]
check_historical_occurence(pos_numbers, winning_numbers)

The combination entered has occurred 1 times in the past.
The probability of winning with [3, 41, 11, 12, 43, 14] is 0.000007%

The function written above will check through all the historical winning numbers and compare how many times the number has occurred in the past, as well as tell the user the likelihood of a combination of numbers will appear in the next drawing.

### Multi-Ticket Probability
Lottery addicts usually play more than one ticket on a single drawing, thinking that this might increase their chances of winning significantly. Since the purpose of the app is to help them better estimate their chances of winning, I built function that will allow the users to calculate the chances of winning for any number of different tickets.

Additional considerations:

- The user will input the number of different tickets they want to play (without inputting the specific combinations they intend to play).
- Our function will see an integer between 1 and 13,983,816 (the maximum number of different tickets). Other lottery will have different number of tickets, but that is beyond the scope of the current project.
- The function should print information about the probability of winning the big prize depending on the number of different tickets played.

In [13]:
def multi_ticket_probability(n):
    tot_outcomes = combinations(49,6)
    probability = n/tot_outcomes
    print('The likelihood of winning with {} tickets is {:.6%}'.format(n, probability))

In [14]:
test = [1, 10, 100, 10000, 1000000, 6991908, 13983816]
for i in test:
    multi_ticket_probability(i)

The likelihood of winning with 1 tickets is 0.000007%
The likelihood of winning with 10 tickets is 0.000072%
The likelihood of winning with 100 tickets is 0.000715%
The likelihood of winning with 10000 tickets is 0.071511%
The likelihood of winning with 1000000 tickets is 7.151124%
The likelihood of winning with 6991908 tickets is 50.000000%
The likelihood of winning with 13983816 tickets is 100.000000%

### Less Winning Numbers
In most 6/49 lotteries, there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. As a consequence, the users might be interested in knowing the probability of having two, three, four, or five winning numbers.

Additional considerations:

- Inside the app, the user inputs:
    - six different numbers from 1 to 49; and
    - an integer between 2 and 5 that represents the number of winning numbers expected
- The function should print information about the probability of having the inputted number of winning numbers.

What if the user wants to calculate the probability of having exactly two winning numbers? I needed to figure out the number of combinations that would contain two numbers from a list of six numbers.

$\binom{\text{total numbers to draw}}{\text{sample}} = \binom{6}{2} = \frac{6!}{2!(6-2)!} = 15$

The last four numbers need to be incorrect. However, the winning numbers from the pool should be removed so that our pool only contains the incorrect numbers:

$\text{total numbers} - \text{winning numbers} = 49 - 6 = 43$

From the 43, I needed to calculate the total number of four number combinations.

$\binom{\text{total incorrect numbers}}{6 - \text{total numbers left to draw}} = \binom{43}{4} = 123,410$

Since there are 15 ways to get two winning number from drawing six numbers, **AND** there are 123,410 ways of getting the rest incorrect, we need to multiply them to get the total number of six number combinations containing at most two winning numbers.

In [15]:
def probability_less_6(n=2):
    n_combinations_ticket = combinations(6, n)
    n_combinations_remaining = combinations(43, 6 - n)
    successful_outcomes = n_combinations_ticket * n_combinations_remaining
    total_outcomes = combinations(49,6)
    prob = successful_outcomes / total_outcomes
    if 2 <= n <=5: 
        print('The likelihood of having a winning {}-number combination is: {:.6%}'.format(n, prob))
    else:
        print('Pick a number between 2 and 5')

In [16]:
test_inputs = [2, 3, 4, 5]

for i in test_inputs:
    probability_less_6(i)

The likelihood of having a winning 2-number combination is: 13.237803%
The likelihood of having a winning 3-number combination is: 1.765040%
The likelihood of having a winning 4-number combination is: 0.096862%
The likelihood of having a winning 5-number combination is: 0.001845%

### Conclusion
The project focused on writing four main functions:
- `one_ticket_probability()` â€” calculates the probability of winning the big prize with a single ticket
- `check_historical_occurrence()` â€” checks whether a certain combination has occurred in the Canada lottery data set
- `multi_ticket_probability()` â€” calculates the probability for any number of of tickets between 1 and 13,983,816
- `probability_less_6()` â€” calculates the probability of having two, three, four or five winning numbers

Possible features for a second version of the app include:

- Making the outputs even easier to understand by adding fun analogies (for example, we can find probabilities for strange events and compare with the chances of winning in lottery; for instance, we can output something along the lines "You are 100 times more likely to be the victim of a shark attack than winning the lottery").
- Combining the one_ticket_probability() and check_historical_occurrence() to output information on probability and historical occurrence at the same time.
- Creating a function similar to probability_less_6() which calculates the probability of having at least two, three, four or five winning numbers.

Additionally, the app should be able to calculate probabilities from additional lottery systems.